/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--md-sys-color-primary)',
          50: 'var(--md-sys-color-primary-50)',
          100: 'var(--md-sys-color-primary-100)',
          200: 'var(--md-sys-color-primary-200)',
          300: 'var(--md-sys-color-primary-300)',
          400: 'var(--md-sys-color-primary-400)',
          500: 'var(--md-sys-color-primary-500)',
          600: 'var(--md-sys-color-primary-600)',
          700: 'var(--md-sys-color-primary-700)',
          800: 'var(--md-sys-color-primary-800)',
          900: 'var(--md-sys-color-primary-900)',
        },
        onPrimary: 'var(--md-sys-color-on-primary)',
        primaryContainer: 'var(--md-sys-color-primary-container)',
        onPrimaryContainer: 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        onSecondary: 'var(--md-sys-color-on-secondary)',
        secondaryContainer: 'var(--md-sys-color-secondary-container)',
        onSecondaryContainer: 'var(--md-sys-color-on-secondary-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        onTertiary: 'var(--md-sys-color-on-tertiary)',
        tertiaryContainer: 'var(--md-sys-color-tertiary-container)',
        onTertiaryContainer: 'var(--md-sys-color-on-tertiary-container)',
        error: 'var(--md-sys-color-error)',
        onError: 'var(--md-sys-color-on-error)',
        errorContainer: 'var(--md-sys-color-error-container)',
        onErrorContainer: 'var(--md-sys-color-on-error-container)',
        background: 'var(--md-sys-color-background)',
        onBackground: 'var(--md-sys-color-on-background)',
        surface: 'var(--md-sys-color-surface)',
        onSurface: 'var(--md-sys-color-on-surface)',
        surfaceVariant: 'var(--md-sys-color-surface-variant)',
        onSurfaceVariant: 'var(--md-sys-color-on-surface-variant)',
        outline: 'var(--md-sys-color-outline)',
        outlineVariant: 'var(--md-sys-color-outline-variant)',
        shadow: 'var(--md-sys-color-shadow)',
        scrim: 'var(--md-sys-color-scrim)',
        inverseSurface: 'var(--md-sys-color-inverse-surface)',
        inverseOnSurface: 'var(--md-sys-color-inverse-on-surface)',
        inversePrimary: 'var(--md-sys-color-inverse-primary)',
        surfaceContainerLowest: 'var(--md-sys-color-surface-container-lowest)',
        surfaceContainerLow: 'var(--md-sys-color-surface-container-low)',
        surfaceContainer: 'var(--md-sys-color-surface-container)',
        surfaceContainerHigh: 'var(--md-sys-color-surface-container-high)',
        surfaceContainerHighest: 'var(--md-sys-color-surface-container-highest)',
      },
    },
  },
  plugins: [],
}
